# Generated by Django 5.0 on 2024-09-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='text',
            new_name='message',
        ),
    ]
